id: push_to_git 
namespace: system
tasks:
  - id: commit_and_push 
    type: io.kestra.plugin.git.PushNamespaceFiles 
    namespace: dev 
    files: "*" 
    gitDirectory: _files 
    url: https://github.com/kestra-io/scripts # required string username: git_username password: "{{ secret('GITHUB_ACCESS_TOKEN') }}" branch: dev commitMessage: "add namespace files"

triggers:
  - id: schedule_push_to_git 
    type: io.kestra.plugin.core.trigger.Schedule 
    cron: "*/15 * * * *" # toutes les 15 minutes
